version: "3"

services:
  portainer:
    container_name: portainer-ce
    image: portainer/portainer-ce:latest
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  portainer_data:
