version: '3.8'

services:
  es01:
    image: hub.hamdocker.ir/elasticsearch:8.12.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
      - http.port=9200
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01-data:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - "9200:9200"

  es02:
    image: hub.hamdocker.ir/elasticsearch:8.12.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es03,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
      - http.port=9200
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02-data:/usr/share/elasticsearch/data
    networks:
      - esnet

  es03:
    image: hub.hamdocker.ir/elasticsearch:8.12.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02,es04
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
      - http.port=9200
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es03-data:/usr/share/elasticsearch/data
    networks:
      - esnet

  es04:
    image: hub.hamdocker.ir/elasticsearch:8.12.1
    container_name: es04
    environment:
      - node.name=es04
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02,es03
      - cluster.initial_master_nodes=es01,es02,es03,es04
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - network.host=0.0.0.0
      - http.port=9200
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es04-data:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: hub.hamdocker.ir/kibana:8.12.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - SERVER_NAME=kibana
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - es01

  # logstash:
  #   image: logstash:8.15.3
  #   container_name: logstash
  #   volumes:
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #   ports:
  #     - "5044:5044"
  #     - "9600:9600"
  #   environment:
  #     - xpack.monitoring.enabled=false
  #   networks:
  #     - esnet
  #   depends_on:
  #     - es01

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/logs:/var/log/nginx
  #     - ./nginx/conf:/etc/nginx/conf.d
  #   networks:
  #     - esnet
  #   ports:
  #     - "8080:80"

  # filebeat:
  #   image: elastic/filebeat:8.15.3
  #   container_name: filebeat
  #   user: root
  #   volumes:
  #     - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - ./nginx/logs:/var/log/nginx
  #   depends_on:
  #     - logstash
  #   networks:
  #     - esnet

volumes:
  es01-data:
  es02-data:
  es03-data:
  es04-data:

networks:
  esnet:
    driver: bridge
