version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:24.0.5
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_SPI_THEME_STATIC_MAX_AGE: 2592000
      KC_SPI_THEME_CACHE_THEMES: false
    volumes:
      - ./plugins/keycloak-mfa-plugins/sms-authenticator/target/sms-authenticator-v25.0.2.jar:/opt/keycloak/providers/sms-authenticator-v25.0.2.jar
    command:
      - start-dev
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 15432:54325
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
