# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:3.6.3
    restart: always
    # environment:
      # MONGO_INITDB_DATABASE: mongo
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
    - mongo-db:/data/db
    ports:
      - 27090:27017
    networks:
      - mongo-net

  # mongo-express:
  #    image: mongo-express
  #    restart: always
  #    ports:
  #      - 8081:8081
  #    networks:
  #      - mongo-net

volumes:
  mongo-db:

networks:
  mongo-net:
